### ISSUE TITLE
Phishing Server IPS

### ISSUE THREAD

**Issue by pentovoid** [mitchellkrogza/phishing#113]
### Domain/URL/IP(s) where you have found the Phishing

```true
188.34.139.235
23.99.65.85
20.94.249.183
52.170.83.27
188.34.139.235
51.116.134.73
104.46.14.154
20.52.2.74
20.109.185.93
20.115.152.112
```

### Describe the issue

There are several server IP addresses opened for phishing purposes. Can you blacklist them?

### Screenshot

<details><summary>Click to expand</summary>

![download](https://user-images.githubusercontent.com/97922239/149846404-f23302e4-a020-4f57-83cd-8c341864b7fe.png)

</details>

**Comment by spirillen** [comment]
Sure, if you provide evidence for each ip and information to reproduce (Confirmation) as adding a IP to a phishing is a devastating thing to do against a IP address and the common trust to that IP-range.

**Comment by pentovoid** [comment]
> Sure, if you provide evidence for each ip and information to reproduce (Confirmation) as adding a IP to a phishing is a devastating thing to do against a IP address and the common trust to that IP-range.

Sure. Look here: https://www.shodan.io/search?query=http.title%3A%22telif%22&page=2

**Comment by pentovoid** [comment]
Also, as I added visually, all IP addresses contain the same image when visited

**Comment by spirillen** [comment]
Maybe it is netter you post a screenshot...

![image](https://user-images.githubusercontent.com/44526987/149847556-6d1aff4b-8b56-498b-bb08-1629f7ba69b1.png)

**Comment by pentovoid** [comment]
![Screenshot from 2022-01-18 02-35-47](https://user-images.githubusercontent.com/97922239/149847771-44165dad-616b-4976-a776-5c62742de4fb.png)

**Comment by spirillen** [comment]
Only half of the IPs seems active

Subject                                                                                              Status      Source     Expiration Date   Registrar                      HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ------------------------------ ---------- -------------
188.34.139.235                                                                                       ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
52.170.83.27                                                                                         ACTIVE      HTTP CODE  Unknown           Unknown                        200        AVAILABILITY 
188.34.139.235                                                                                       ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
23.99.65.85                                                                                          INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
104.46.14.154                                                                                        INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
51.116.134.73                                                                                        INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY

**Comment by pentovoid** [comment]
Can you try by registering on Shodan.io?

**Comment by pentovoid** [comment]
They blocked access outside of Turkey to avoid detection. I'm in Turkey and I can access
