### ISSUE TITLE
False positives and list(s)

### ISSUE THREAD

**Issue by spirillen** [mitchellkrogza/phishing#226]
In reply to https://github.com/mitchellkrogza/phishing/pull/213 we might fase an issue with only one falsepositive or exclusion list as there are both wildcard and full-match only cases.

The falsepositive list is used as a wildcard list right?

If I remember that right :arrow_double_up: this is calling for a new exclusion lists that takes "this match" only which in general might be a good idea, as there are other freely sub-domain hosting services out there.

Alternative is we start demanding people reads and understand the [whitelist-tools commands](https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/script/README.rst#special-markers) for `ALL` | `REG` | `RZD` etc and have them applying it into one lists. 

I therefor suggestion the project will be using two whitelists to simplify contributions to this project.

**Comment by funilrys** [comment]
@spirillen suggestion approved. Please go ahead. 
Ping me if you need my support.
