### ISSUE TITLE
vodafone.de

### ISSUE THREAD

**Issue by rika-0x** [mitchellkrogza/phishing#241]
### Domain/URL/IP(s) you believes NOT to be Phishing

```CSS
vodafone.de
live.vodafone.de

https://live.vodafone.de
https://www.vodafone.de/cprx/captcha
https://www.vodafone.de/meinvodafone/account/login?protocol=oidc
```

### Whitelist type

- [ ] `1 to 1` match
- [ ] `ALL` subdomains or `REGEX`
- [X] `RZD` all sub- and top level domains matching given record(s)

### More Information

- [ ] mitchellkrogza Phishing
- [X] mitchellkrogza Phishing.Database
- [ ] Website was hacked
- [ ] Listed as Phishing on Phishtank or OpenPhish
- [ ] Listed on VirusTotal
- [ ] Other (Please tell us where in *Related external source* below)

### Describe the issue

Found in ALL-phishing-domains and ALL-phishing-links archives. Not a phishing site and doesn't seem to have been hacked recently. VirusTotal shows no hits (Even for Phishing.Database weirdly enough)

Any idea how these got reported as phishing? I'm guessing these archives are already filtered with your whitelist, correct?

**Comment by spirillen** [comment]
> Any idea how these got reported as phishing?


>  I'm guessing these archives are already filtered with your whitelist, correct?

There seems to be situations from time to time where there are some mistakes by running the whitelist through the final phishing list for cleanup.

I will add this one to the whitelist
