### ISSUE TITLE
Invalid detection

### ISSUE THREAD

**Issue by jeyashree-n** [mitchellkrogza/phishing#352]
### Domain/URL/IP(s) you believe NOT to be Phishing

```CSS
surveysparrow.com
```

### Whitelist type

- [ ] `1 to 1` match
- [X] `ALL` subdomains or `REGEX`
- [ ] `RZD` all sub- and top level domains matching given record(s)

### More Information

- [ ] Website was hacked
- [ ] Phishtank
- [ ] OpenPhish
- [ ] VirusTotal
- [x] Other (Please fill out the next box)

### Additional context

```Text
This is a survey platform. However, the global domain is marked as phishing. Not a phishing site.

Any idea how these got reported as phishing?
```

**Comment by spirillen** [comment]
> Any idea how these got reported as phishing?

Me, nope, maybe @mitchellkrogza have something about it
