### ISSUE TITLE
leadslitmus.com

### ISSUE THREAD

**Issue by TechArea** [mitchellkrogza/phishing#500]
### Phishing Domain/URL/IP(s)

```Markdown
leadslitmus.com
```

### Impersonated domain

```CSS
leadslitmus.com
```

### Describe your experience.

The sender tries to encourage the user to interact by making banal requests in order to obtain information.

### Screenshot

<details><summary>Screenshot, Impersonated site</summary>

![CleanShot 2024-10-17 at 19 18 15@2x](https://github.com/user-attachments/assets/3a4bced8-fe78-4e07-ae3c-56ff3a54e319)

</details>

**Comment by spirillen** [comment]
> Hi @TechArea Thanks for creating the issue at both here and https://github.com/mitchellkrogza/phishing/issues/500 as well.
> 
> There is one thins however that strikes me and needs to be clarified for submission.
> 
> The only place I see the domain `leadslitmus.com`, is in what appears to be the sending domain for the mail. So are you kind to share the full mail source/header to backtrack this for confirmation? I would hate adding a innocent to a phishing list, just because their domain have been spoofed in a Phishing mail
> 
> source: https://kb.mypdns.org/issue/MTX-1195/leadslitmus.com#focus=Comments-4-261.0-0

**Comment by spirillen** [comment]
See full comment for **not** adding this domain at https://kb.mypdns.org/issue/MTX-1195/leadslitmus.com#focus=Comments-4-263.0-0
