### ISSUE TITLE
Phishing IP

### ISSUE THREAD

**Issue by hellyeahs** [mitchellkrogza/phishing#55]
212.64.215.12

I request you to blacklist the IP address. Again, the domains connected to this IP address are listed. I will PR

**Comment by spirillen** [comment]
Hi @hellyeahs I'll be very open to submit the IP address, we just need some more proof like a screenshot and/or some words or sources with needed info for proof in https://mypdns.org/my-privacy-dns/matrix/-/issues/2961#relevant-logs-andor-screenshots

I prepared this MR to you @hellyeahs https://mypdns.org/my-privacy-dns/matrix/-/merge_requests/2

**Comment by hellyeahs** [comment]
New Phishing IP **212.64.215.197**

**Comment by spirillen** [comment]
@hellyeahs please post them directly to https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issuable_template=IP%20Blocking with small comment of why or from where you have the information so everyone can challenge the information.

Wee will also have to get @mitchellkrogza in, to determine if he wants his own IP lists and if yes, how it should be formatted.
